name: "Devel Build"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Generate test requirements
        run: >
          poetry export
          -f requirements.txt
          -o $OUTPUT_DIR/requirements.test.txt
          --without-hashes
          --without-urls
          --with test
          --with server

      - name: Install TOX
        run: |
          pip install tox

      - name: Run Unittests
        id: unittests-run
        run: |
          tox

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-report.xml

#  build-job-lite:
#    needs: run-unittests
#    runs-on: ubuntu-latest
#
#  build-job:
#    needs: run-unittests
#    runs-on: ubuntu-latest



