name: "Devel Build"

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  run-unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Generate test requirements
        run: >
          poetry export
          -f requirements.txt
          -o requirements.test.txt
          --without-hashes
          --without-urls
          --with test
          --with server

      - name: Install TOX
        run: |
          pip install tox

      - name: Run Unittests
        id: unittests-run
        run: |
          tox

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-report.xml

#      - name: SonarCloud Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-package:
    needs: run-unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Generate server requirements
        run: >
          poetry export
          -f requirements.txt
          -o requirements.server.txt
          --without-hashes
          --without-urls
          --with server

      - name: Build Package
        run: |
          poetry build --format=wheel
          cp requirements.server.txt dist/requirements.txt
          cp -r scripts/ dist/
          ls -la dist/

      - name: Save wheel
        uses: actions/upload-artifact@v4
        with:
          name: freeze
          path: dist/

  build-job-engine:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: freeze
          path: dist/

      - name: SetUp QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.SIXSQ_DOCKER_USERNAME }}
          password: ${{ secrets.SIXSQ_DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          build-args: |
            GIT_BRANCH=${{ github.head_ref || github.ref_name }}
            GIT_BUILD_TIME=$(date --utc +%FT%T.%3NZ)
            GIT_COMMIT_ID=${{ github.sha }}
            GITHUB_RUN_NUMBER=${{ github.run_number }}
            GITHUB_RUN_ID=${{ github.run_id }}
            PROJECT_URL=${{ github.server_url }}/${{ github.repository }}
            PACKAGE_NAME=${{ env.PACKAGE_NAME }}
          push: true
          tags: >
            nuvladev/${{ github.event.repository.name }}:${{ github.head_ref || github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


#  build-job-lite:
#    needs: run-unittests
#    runs-on: ubuntu-latest
#
#  build-job:
#    needs: run-unittests
#    runs-on: ubuntu-latest



