name: BUILD

on: [push, pull_request, workflow_dispatch]

jobs:

  job-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            - name: Cache local Maven repository

      - name: Multi-arch docker image build prerequired
        run: sudo docker run --privileged linuxkit/binfmt:v0.7

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install pytest
        run: |
          python3 -m pip install --upgrade pytest

      - name: Install test requirements
        run: |
          python3 -m pip install --upgrade -r code/requirements.test.txt

      - name: Make internal packages part of nuvla-api distribution
        run: |
          export SITE_PACKAGES=$(dirname $(python3 -c 'import os; print(os.__file__)'))/site-packages
          ln -sf $(pwd)/code/src/nuvla/connector $SITE_PACKAGES/nuvla/
          ln -sf $(pwd)/code/src/nuvla/job $SITE_PACKAGES/nuvla/

      - uses: s4u/maven-settings-action@v2.2.0
        with:
          githubServer: false
          override: true
          servers: |
            [{
                "id": "docker.io",
                "username": "${{ secrets.SIXSQ_DOCKER_USERNAME }}",
                "password": "${{ secrets.SIXSQ_DOCKER_PASSWORD }}"
            }]

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      - name: Build with Maven
        env:
          TRAVIS_BRANCH: ${{ steps.extract_branch.outputs.branch }}
          TRAVIS_PULL_REQUEST_BRANCH: ${{ github.head_ref }}
          TRAVIS_BUILD_NUMBER: ${{ github.run_id }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SIXSQ_DOCKER_USERNAME: ${{ secrets.SIXSQ_DOCKER_USERNAME }}
          SIXSQ_DOCKER_PASSWORD: ${{ secrets.SIXSQ_DOCKER_PASSWORD }}
        run: mvn deploy

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: code/test-report.xml

  job-notify:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - job-build
    runs-on: ubuntu-latest
    steps:
      - uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
